# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rfaster2_wrappers", use_symbols = TRUE, package_name = "rfaster2")

#' @usage NULL
#' @useDynLib rfaster2, .registration = TRUE
NULL

#' Return vector of fastq read lengths
#'@export
fq_lengths <- function(infile) .Call(wrap__fq_lengths, infile)

#' Return vector of 'mean' fastq read quality values
#' @export
#' Return number of reads in a fastq file
#' @export
fq_nreads <- function(infile) .Call(wrap__fq_nreads, infile)

#' Return number of bases in a fastq file
#' @export
fq_nbases <- function(infile) .Call(wrap__fq_nbases, infile)


# nolint end
