# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rfaster2_wrappers", use_symbols = TRUE, package_name = "rfaster2")

#' @usage NULL
#' @useDynLib rfaster2, .registration = TRUE
NULL

#' FASTQ read lengths
#' 
#' Obtain read lengths from a fastq/fastq.gz file 
#' 
#' @param infile Path to fastq/fastq.gz file
#' @return Numeric vector with fastq records lengths
#' @export
fq_lengths <- function(infile) .Call(wrap__fq_lengths, infile)

#' FASTQ 'mean' quality scores
#' 
#' Obtain'mean' fastq read quality values. Mean Phred scores are calculated by converting to probabiliy, calculating mean quality, then converting back to Phred.
#' 
#' @param infile Path to fastq/fastq.gz file
#' @param phred Logical, report Phred score (error probability otherwise)
#' @return Numeric vector with 'mean' quality score per read
#' @export
fq_quals <- function(infile, phred) .Call(wrap__fq_quals, infile, phred)

#' FASTQ number of reads
#' 
#' Obtain the number of reads in a fastq/fastq.gz file
#' 
#' @param infile Path to fastq/fastq.gz file
#' @return Numeric 
#' @export
fq_reads <- function(infile) .Call(wrap__fq_reads, infile)

#' FASTQ number of bases
#' 
#' Obtain the number of bases in a fastq/fastq.gz file
#' 
#' @param infile Path to fastq/fastq.gz file
#' @return Numeric
#' @export
fq_bases <- function(infile) .Call(wrap__fq_bases, infile)

#' Return vector with summary values for the fastq file, this is not exported in the R package namespace
rust_summary <- function(infile) .Call(wrap__rust_summary, infile)


# nolint end
